CXX = g++
CPPFLAGS =--std=c++11
  
  
   
compilacion: compilacion
	$(CXX) $(CPPFLAGS) insercion.cpp -o insercion
	$(CXX) $(CPPFLAGS) propio.cpp -o propio
	$(CXX) $(CPPFLAGS) cercania.cpp -o cercania
	$(CXX) $(CPPFLAGS) asignacionTareas.cpp -o asignacionTareas		

	


# ************ Limpieza ************
clean :
	-rm insercion propio cercania asignacionTareas
	

